dist: trusty
sudo: required

language: scala

scala:
   - 2.11.11
jdk:
  - jdk8
  - openjdk8

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

services:
  - docker

matrix:
  fast_finish: true
  include:
    - language: python
      python: 2.7

      install:
        - make build
        - mkdir -p python/jars
        - cp target/**/spark-api-uber.jar python/jars
        - cd python
        - pip install -r requirements.txt

      script:
        - python -m unittest discover -v

      after_success:
        - echo "" # noop to avoid executing the one from the main build

    - language: python
      python: 3.6

      install:
        - make build
        - mkdir -p python/jars
        - cp target/**/spark-api-uber.jar python/jars
        - cd python
        - pip install -r requirements.txt

      script:
        - python -m unittest discover -v

      after_success:
        - echo "" # noop to avoid executing the one from the main build

before_script:
  - docker run --privileged -d -p 9432:9432 --name bblfsh bblfsh/server

script:
  - make travis-test
  - make build

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - echo "$TRAVIS_TAG" | cut -c 2- > version.txt

deploy:
  - provider: script
    script: make docker-push
  - provider: pypi
    user: $PYPI_USERNAME
    password: $PYPI_PASSWORD
  skip_cleanup: true
  on:
    tags: true
