dist: trusty
sudo: required

language: scala

scala:
   - 2.11.11

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2
    - .spark-dist

services:
  - docker

matrix:
  fast_finish: true
  include:
    - jdk: jdk8

      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - openssl aes-256-cbc -K $encrypted_8a9ac81f2640_key -iv $encrypted_8a9ac81f2640_iv -in key.asc.enc -out key.asc -d
        - gpg --no-default-keyring --primary-keyring ./project/.gnupg/pubring.gpg --secret-keyring ./project/.gnupg/secring.gpg --keyring ./project/.gnupg/pubring.gpg --fingerprint --import key.asc
        - cp target/engine-uber.jar "engine-$TRAVIS_TAG.jar"

      deploy:
        - provider: script
          script: make docker-push && make maven-release
          skip_cleanup: true
          on:
            tags: true
        - provider: releases
          api_key:
            secure: $GITHUB_TOKEN
          file_glob: true
          file: "*.jar"
          skip_cleanup: true
          on:
            tags: true

    - jdk: openjdk8

    - jdk: openjdk8

      env:
        - END_TO_END=true

      before_script:
        - make docker-bblfsh

      script:
        - make build
        - ./_tools/getApacheSpark.sh "2.2.0" "2.7"
        - ./spark/bin/spark-shell --jars ./target/engine-uber.jar -i src/test/resources/SparkShellScript.scala

    - language: python
      python: 2.7

      install:
        - make build
        - mkdir -p python/jars
        - cp target/engine-uber.jar python/jars
        - cd python
        - pip install -r requirements.txt

      script:
        - python -m unittest discover -v

    - language: python
      python: 3.6

      install:
        - make build
        - mkdir -p python/jars
        - cp target/engine-uber.jar python/jars
        - cd python
        - pip install -r requirements.txt

      script:
        - python -m unittest discover -v

      before_deploy:
        - echo "$TRAVIS_TAG" | cut -c 2- > version.txt

      deploy:
        - provider: pypi
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          skip_cleanup: true
          on:
            tags: true

before_script:
  - make docker-bblfsh

script:
  - make travis-test
  - make build
