dist: trusty
sudo: required

language: scala

scala:
   - 2.11.11

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2

services:
  - docker

matrix:
  fast_finish: true
  include:
    - jdk: jdk8

      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - openssl aes-256-cbc -K $encrypted_8a9ac81f2640_key -iv $encrypted_8a9ac81f2640_iv -in key.asc.enc -out key.asc -d
        - gpg --no-default-keyring --primary-keyring ./project/.gnupg/pubring.gpg --secret-keyring ./project/.gnupg/secring.gpg --keyring ./project/.gnupg/pubring.gpg --fingerprint --import key.asc
        - cp target/engine-uber.jar "engine-$TRAVIS_TAG.jar"

      deploy:
        - provider: script
          script: make docker-push && make maven-release
          skip_cleanup: true
          on:
            tags: true
        - provider: releases
          api_key:
            secure: $GITHUB_TOKEN
          file_glob: true
          file: "*.jar"
          skip_cleanup: true
          on:
            tags: true

    - jdk: openjdk8

    - language: python
      python: 2.7

      install:
        - make build
        - cd python
        - pip install -r requirements.txt

      script:
        - make test

    - language: python
      python: 3.6

      install:
        - make build
        - cd python
        - pip install -r requirements.txt

      script:
        - make test

      before_deploy:
        - echo "$TRAVIS_TAG" | cut -c 2- > version.txt

      deploy:
        - provider: pypi
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          skip_cleanup: true
          on:
            tags: true

before_script:
  - make -f "$TRAVIS_BUILD_DIR/Makefile" docker-bblfsh
  - make -f "$TRAVIS_BUILD_DIR/Makefile" docker-bblfsh-install-drivers

script:
  - make travis-test
